### PR TITLE
Update cgf.13721

### PR DESCRIPTION
**Pull request by alex-rind**
resources for Stoiber et al.: netflower

### CODE REVIEW

**Comment by Dev-Lan** [comment]
Thanks so much for adding some resources! It seems like this URL may be missing something though? I am getting a 403 error?

https://phaidra.fhstp.ac.at/download/o

**Comment by alex-rind** [comment]
The complete url is <https://phaidra.fhstp.ac.at/download/o:4838>.

**Comment by alex-rind** [comment]
url escaping could work:  https://phaidra.fhstp.ac.at/download/o%3A4838

**Comment by Dev-Lan** [comment]
Ah my mistake, I just misread it. Thanks for the clarification!

**Pull request merged**
